global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['backend:8000']
  - job_name: 'fastapi-local'
    static_configs:
      - targets: ['host.docker.internal:8000'] 